version: '3'

services:
  app:
    build: .
    environment:
      DB_HOST: postgres 
    ports:
      - 8000:8000

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432